apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root

spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: require-non-root

      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Containers must not run as root."

        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true]
